#!/bin/sh

set -ex

if [ -z "$TMPDIR"]; then
    export TMPDIR=/tmp
fi

git clone --depth 1 --single-branch git://github.com/libgit2/libgit2 "$TMPDIR/libgit2"

cd "$TMPDIR/libgit2"
cmake -DTHREADSAFE=ON \
      -DBUILD_CLAR=OFF \
      -DCMAKE_INSTALL_PREFIX=$PWD/install \
      .

make install

# Let the Go build system know where to find libgit2
export LD_LIBRARY_PATH="$TMPDIR/libgit2/install/lib"
export PKG_CONFIG_PATH="$TMPDIR/libgit2/install/lib/pkgconfig"

cd $OLDPWD

go test
